services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-taxprotest}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
      POSTGRES_DB: ${POSTGRES_DB:-taxprotest}
    ports:
      - "6385:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxprotest"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    ports:
      - "8020:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-taxprotest}:${POSTGRES_PASSWORD:-change-me}@db:5432/${POSTGRES_DB:-taxprotest}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=${DEBUG:-0}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0,property.ohmygoshwhatever.com}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-https://property.ohmygoshwhatever.com}
      - USE_X_FORWARDED_HOST=${USE_X_FORWARDED_HOST:-1}
      - ENABLE_SECURE_PROXY_SSL_HEADER=${ENABLE_SECURE_PROXY_SSL_HEADER:-1}
      - FORCE_SECURE_COOKIES=${FORCE_SECURE_COOKIES:-1}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-3}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn taxprotest.wsgi:application --bind 0.0.0.0:8000 --workers ${WEB_CONCURRENCY:-3}"

  # Celery worker for processing background tasks
  worker:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-taxprotest}:${POSTGRES_PASSWORD:-change-me}@db:5432/${POSTGRES_DB:-taxprotest}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=${DEBUG:-0}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: celery -A taxprotest worker --loglevel=info

  # Celery beat for scheduled tasks (runs monthly imports)
  beat:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-taxprotest}:${POSTGRES_PASSWORD:-change-me}@db:5432/${POSTGRES_DB:-taxprotest}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=${DEBUG:-0}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: celery -A taxprotest beat --loglevel=info

volumes:
  pgdata:
    driver: local

