services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: taxprotest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxprotest
    ports:
      - "6385:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxprotest"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://taxprotest:password@db:5432/taxprotest
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # Example worker service (optional). Uncomment and adjust if you want to run celery workers
  # worker:
  #   build: .
  #   command: celery -A taxprotest worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - db

volumes:
  pgdata:
    driver: local
