# Generated by Django 5.2.7 on 2025-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_property_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyrecord',
            name='property_zip_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyrecord',
            name='property_addr_idx',
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='assessed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='building_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='owner_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='street_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='street_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
