# Generated by Django 5.2.7 on 2025-10-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_propertyrecord_prop_zip_street_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='parcel_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
