# Generated by Django 5.2.11 on 2026-02-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_buildingdetail_import_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrecord',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='buildingdetail',
            constraint=models.UniqueConstraint(fields=('account_number', 'building_number'), name='unique_building_per_account'),
        ),
        migrations.AddConstraint(
            model_name='extrafeature',
            constraint=models.UniqueConstraint(fields=('account_number', 'feature_code', 'feature_number'), name='unique_feature_per_account'),
        ),
    ]
