# Generated by Codex on 2026-05-02

from django.db import migrations


TRIGRAM_INDEXES = (
    ("data_property_owner_trgm_idx", "owner_name"),
    ("data_property_address_trgm_idx", "address"),
    ("data_property_street_trgm_idx", "street_name"),
    ("data_property_zipcode_trgm_idx", "zipcode"),
)


def create_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for index_name, column_name in TRIGRAM_INDEXES:
        schema_editor.execute(
            f'CREATE INDEX IF NOT EXISTS "{index_name}" '
            f'ON "data_propertyrecord" USING gin ("{column_name}" gin_trgm_ops)'
        )


def drop_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    for index_name, _ in reversed(TRIGRAM_INDEXES):
        schema_editor.execute(f'DROP INDEX IF EXISTS "{index_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_propertyrecord_is_data_ready_and_more"),
    ]

    operations = [
        migrations.RunPython(create_trigram_indexes, drop_trigram_indexes),
    ]
