# Generated by Django 5.2.14 on 2026-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0014_assessmenthistory_cap_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyJurisdictionExemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_number", models.CharField(db_index=True, max_length=20)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("tax_unit_code", models.CharField(db_index=True, max_length=32)),
                ("tax_unit_name", models.CharField(blank=True, max_length=255)),
                ("exemption_code", models.CharField(blank=True, max_length=32)),
                ("exemption_description", models.CharField(blank=True, max_length=255)),
                (
                    "exemption_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "exemption_percent",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                (
                    "taxable_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "assessed_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account_number", "tax_year"], name="data_proper_account_07f208_idx"
                    ),
                    models.Index(
                        fields=["tax_year", "tax_unit_code"], name="data_proper_tax_yea_0a0597_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_number", "tax_year", "tax_unit_code", "exemption_code"),
                        name="unique_jur_exemption_per_unit_code_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxUnitRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tax_year", models.IntegerField(db_index=True)),
                ("tax_unit_code", models.CharField(db_index=True, max_length=32)),
                ("tax_unit_name", models.CharField(blank=True, max_length=255)),
                ("adopted_rate", models.DecimalField(decimal_places=8, max_digits=12)),
                ("source", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tax_year", "tax_unit_code"], name="data_taxuni_tax_yea_0c3fe8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tax_year", "tax_unit_code"), name="unique_tax_rate_per_unit_year"
                    )
                ],
            },
        ),
    ]
