# Generated by Django 5.2.16 on 2026-07-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_propertyjurisdictionexemption_taxunitrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrazosImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tax_year", models.IntegerField(db_index=True)),
                ("source_url", models.TextField(blank=True)),
                ("archive_name", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="running", max_length=32)),
                ("rows_loaded", models.BigIntegerField(default=0)),
                ("rows_rejected", models.BigIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prop_id", models.BigIntegerField(db_index=True)),
                ("prop_type_cd", models.CharField(blank=True, db_index=True, max_length=5)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("sup_num", models.BigIntegerField(blank=True, null=True)),
                ("geo_id", models.CharField(blank=True, db_index=True, max_length=50)),
                ("py_owner_id", models.BigIntegerField(blank=True, null=True)),
                ("owner_name", models.CharField(blank=True, db_index=True, max_length=70)),
                ("owner_addr_line1", models.CharField(blank=True, max_length=60)),
                ("owner_addr_line2", models.CharField(blank=True, max_length=60)),
                ("owner_addr_line3", models.CharField(blank=True, max_length=60)),
                ("owner_addr_city", models.CharField(blank=True, max_length=50)),
                ("owner_addr_state", models.CharField(blank=True, max_length=50)),
                ("owner_addr_zip", models.CharField(blank=True, max_length=5)),
                ("situs_street_prefix", models.CharField(blank=True, max_length=10)),
                ("situs_street", models.CharField(blank=True, db_index=True, max_length=50)),
                ("situs_street_suffix", models.CharField(blank=True, max_length=10)),
                ("situs_city", models.CharField(blank=True, db_index=True, max_length=30)),
                ("situs_zip", models.CharField(blank=True, db_index=True, max_length=10)),
                ("legal_desc", models.CharField(blank=True, max_length=255)),
                ("legal_desc2", models.CharField(blank=True, max_length=255)),
                (
                    "legal_acreage",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("abs_subdv_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("hood_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("block", models.CharField(blank=True, max_length=50)),
                ("tract_or_lot", models.CharField(blank=True, max_length=50)),
                (
                    "land_hstd_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "land_non_hstd_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "imprv_hstd_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "imprv_non_hstd_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "ag_use_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "ag_market",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "timber_use",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "timber_market",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "appraised_val",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "ten_percent_cap",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "assessed_val",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("arb_protest_flag", models.BooleanField(blank=True, null=True)),
                ("deed_dt", models.CharField(blank=True, max_length=25)),
                ("hs_exempt", models.BooleanField(blank=True, null=True)),
                ("ov65_exempt", models.BooleanField(blank=True, null=True)),
                ("dp_exempt", models.BooleanField(blank=True, null=True)),
                ("imprv_state_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("land_state_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("personal_state_cd", models.CharField(blank=True, max_length=10)),
                (
                    "land_acres",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="data_proper_tax_yea_75c673_idx"
                    ),
                    models.Index(
                        fields=["tax_year", "hood_cd"], name="data_proper_tax_yea_6a6ddd_idx"
                    ),
                    models.Index(
                        fields=["tax_year", "situs_city"], name="data_proper_tax_yea_218ffa_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year"), name="unique_brazos_account_per_year"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyEntity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entity_id", models.BigIntegerField(db_index=True)),
                ("entity_cd", models.CharField(blank=True, db_index=True, max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "property entities",
                "constraints": [
                    models.UniqueConstraint(fields=("entity_id",), name="unique_brazos_entity")
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyImprovement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prop_id", models.BigIntegerField(db_index=True)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("imp_id", models.BigIntegerField(db_index=True)),
                ("imprv_type_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("imprv_type_desc", models.CharField(blank=True, max_length=25)),
                ("imprv_state_cd", models.CharField(blank=True, db_index=True, max_length=5)),
                ("imprv_homesite", models.BooleanField(blank=True, null=True)),
                (
                    "imprv_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "imprv_homesite_pct",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("omitted", models.BooleanField(blank=True, null=True)),
                (
                    "omitted_imprv_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="data_proper_tax_yea_bf7e12_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year", "imp_id"), name="unique_brazos_improvement"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyImprovementDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prop_id", models.BigIntegerField(db_index=True)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("imp_id", models.BigIntegerField(db_index=True)),
                ("imprv_det_id", models.BigIntegerField(db_index=True)),
                ("imprv_det_type_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("imprv_det_type_desc", models.CharField(blank=True, max_length=25)),
                ("imprv_det_class_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("yr_built", models.IntegerField(blank=True, db_index=True, null=True)),
                ("depreciation_yr", models.IntegerField(blank=True, null=True)),
                (
                    "imprv_det_area",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "imprv_det_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("sketch_cmds", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="data_proper_tax_yea_322ac4_idx"
                    ),
                    models.Index(
                        fields=["tax_year", "imp_id"], name="data_proper_tax_yea_6adbab_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year", "imp_id", "imprv_det_id"),
                        name="unique_brazos_improvement_detail",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyLand",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("prop_id", models.BigIntegerField(db_index=True)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("land_seg_id", models.BigIntegerField(db_index=True)),
                ("land_type_cd", models.CharField(blank=True, db_index=True, max_length=10)),
                ("land_type_desc", models.CharField(blank=True, max_length=25)),
                ("state_cd", models.CharField(blank=True, db_index=True, max_length=5)),
                ("land_seg_homesite", models.BooleanField(blank=True, null=True)),
                (
                    "size_acres",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "size_square_feet",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "effective_front",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "effective_depth",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("mkt_ls_method", models.CharField(blank=True, max_length=5)),
                ("mkt_ls_class", models.CharField(blank=True, max_length=10)),
                (
                    "land_seg_mkt_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("ag_apply", models.BooleanField(blank=True, null=True)),
                ("ag_ls_method", models.CharField(blank=True, max_length=5)),
                ("ag_ls_class", models.CharField(blank=True, max_length=10)),
                (
                    "ag_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "land_homesite_pct",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="data_proper_tax_yea_ed0988_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year", "land_seg_id"),
                        name="unique_brazos_land_segment",
                    )
                ],
            },
        ),
    ]
