# Generated by Django 5.2.16 on 2026-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_brazosimportrun_export_dataset_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyaccount",
            name="latitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="longitude",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="parcel_area_sqft",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name="propertyaccount",
            index=models.Index(
                fields=["tax_year", "latitude", "longitude"], name="data_proper_tax_yea_5d5716_idx"
            ),
        ),
    ]
