# Generated by Django 5.2.17 on 2026-08-06 04:20

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prop_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("situs_address", models.CharField(blank=True, max_length=255)),
                ("situs_city", models.CharField(blank=True, max_length=100)),
                ("situs_state", models.CharField(blank=True, max_length=2)),
                ("situs_zip", models.CharField(blank=True, max_length=10)),
                ("owner_name", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "land_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "improvement_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "assessed_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("state_class", models.CharField(blank=True, db_index=True, max_length=10)),
                (
                    "is_residential",
                    models.BooleanField(db_default=False, db_index=True, default=False),
                ),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Account",
                "verbose_name_plural": "BCAD Property Accounts",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="brazos_cad__tax_yea_004f8d_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year"), name="brazoscad_account_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("entity_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("entity_type", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "adopted_rate",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Entity",
                "verbose_name_plural": "BCAD Property Entities",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "entity_id"], name="brazos_cad__tax_yea_0d98cb_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_id", "tax_year"), name="brazoscad_entity_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prop_id", models.CharField(db_index=True, max_length=32)),
                ("imp_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("improvement_type", models.CharField(blank=True, db_index=True, max_length=16)),
                ("improvement_description", models.CharField(blank=True, max_length=128)),
                (
                    "improvement_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("year_built", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "square_feet",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Improvement",
                "verbose_name_plural": "BCAD Property Improvements",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="brazos_cad__tax_yea_dc532c_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("imp_id", "tax_year"), name="brazoscad_improvement_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyImprovementDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("imp_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("detail_seq", models.IntegerField(db_index=True, default=0)),
                ("detail_description", models.CharField(blank=True, max_length=255)),
                (
                    "detail_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "detail_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("detail_unit", models.CharField(blank=True, max_length=32)),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Improvement Detail",
                "verbose_name_plural": "BCAD Property Improvement Details",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "imp_id"], name="brazos_cad__tax_yea_402918_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("imp_id", "tax_year", "detail_seq"),
                        name="brazoscad_improvement_detail_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prop_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("land_seq", models.IntegerField(db_index=True, default=0)),
                ("land_use_code", models.CharField(blank=True, db_index=True, max_length=16)),
                ("land_use_description", models.CharField(blank=True, max_length=128)),
                (
                    "acreage",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "land_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Land",
                "verbose_name_plural": "BCAD Property Lands",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="brazos_cad__tax_yea_809700_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "tax_year", "land_seq"), name="brazoscad_land_unique"
                    )
                ],
            },
        ),
    ]
