# Generated by Django 5.2.17 on 2026-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="propertyimprovement",
            name="brazoscad_improvement_unique",
        ),
        migrations.RemoveConstraint(
            model_name="propertyimprovementdetail",
            name="brazoscad_improvement_detail_unique",
        ),
        migrations.AddField(
            model_name="propertyimprovementdetail",
            name="prop_id",
            field=models.CharField(db_index=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="propertyimprovementdetail",
            name="detail_unit",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="propertyimprovement",
            constraint=models.UniqueConstraint(
                fields=("prop_id", "imp_id", "tax_year"), name="brazoscad_improvement_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimprovementdetail",
            constraint=models.UniqueConstraint(
                fields=("prop_id", "imp_id", "tax_year", "detail_seq"),
                name="brazoscad_improvement_detail_unique",
            ),
        ),
    ]
