# Generated by Django 5.2.17 on 2026-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0002_remove_propertyimprovement_brazoscad_improvement_unique_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyentity",
            name="adopted_rate",
        ),
        migrations.RemoveField(
            model_name="propertyentity",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="propertyentity",
            name="entity_name",
        ),
        migrations.RemoveField(
            model_name="propertyentity",
            name="entity_type",
        ),
        migrations.AddField(
            model_name="propertyentity",
            name="entity_code",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
