# Generated by Django 5.2.17 on 2026-08-09 00:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0004_propertyaccount_class_code_propertyaccount_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyBuildingCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prop_id", models.CharField(db_index=True, max_length=32)),
                ("imp_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("half_baths", models.IntegerField(blank=True, null=True)),
                ("room_count", models.IntegerField(blank=True, null=True)),
                ("exterior_wall", models.CharField(blank=True, max_length=64)),
                ("foundation", models.CharField(blank=True, max_length=64)),
                ("roof_covering", models.CharField(blank=True, max_length=64)),
                ("heating_cooling", models.CharField(blank=True, max_length=64)),
                ("interior_finish", models.CharField(blank=True, max_length=64)),
                ("construction_style", models.CharField(blank=True, max_length=64)),
                ("flooring", models.CharField(blank=True, max_length=64)),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Building Characteristic",
                "verbose_name_plural": "BCAD Property Building Characteristics",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="brazos_cad__tax_yea_3029b4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prop_id", "imp_id", "tax_year"),
                        name="brazoscad_building_characteristic_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyExtraFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prop_id", models.CharField(db_index=True, max_length=32)),
                ("imp_id", models.CharField(db_index=True, max_length=32)),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("detail_seq", models.IntegerField(db_index=True, default=0)),
                ("feature_type", models.CharField(db_index=True, max_length=64)),
                ("feature_value", models.CharField(blank=True, max_length=64)),
                ("source_file", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "verbose_name": "BCAD Property Extra Feature",
                "verbose_name_plural": "BCAD Property Extra Features",
                "indexes": [
                    models.Index(
                        fields=["tax_year", "prop_id"], name="brazos_cad__tax_yea_e4f3d5_idx"
                    ),
                    models.Index(fields=["feature_type"], name="brazos_cad__feature_9a5927_idx"),
                ],
            },
        ),
    ]
