# Generated by Django 5.2.17 on 2026-08-15 19:50

from django.db import migrations


def backfill_parcel_geometry_from_brazos(apps, schema_editor):
    """Copy lat/long from PropertyAccount into ParcelGeometry."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO data_parcelgeometry
                (account_number, county, latitude, longitude, parcel_id, created_at, updated_at)
            SELECT DISTINCT ON (prop_id)
                   prop_id, 'brazos', latitude, longitude, '', NOW(), NOW()
            FROM brazos_cad_propertyaccount
            WHERE latitude IS NOT NULL AND longitude IS NOT NULL
            ORDER BY prop_id, tax_year DESC
            ON CONFLICT (account_number, county) DO NOTHING
        """)


def remove_brazos_parcel_geometry(apps, schema_editor):
    ParcelGeometry = apps.get_model("data", "ParcelGeometry")
    ParcelGeometry.objects.filter(county="brazos").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0005_propertybuildingcharacteristic_propertyextrafeature"),
        ("data", "0017_parcelgeometry"),
    ]

    operations = [
        migrations.RunPython(backfill_parcel_geometry_from_brazos, remove_brazos_parcel_geometry),
    ]