# Generated by Django 5.2.17 on 2026-08-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0005_propertybuildingcharacteristic_propertyextrafeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyaccount",
            name="coordinate_source",
            field=models.CharField(blank=True, db_default="", max_length=64),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="coordinate_source_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
