# Generated by Django 5.2.17 on 2026-08-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0006_backfill_parcelgeometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyaccount",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="propertyaccount",
            name="longitude",
        ),
    ]
