# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0006_propertyaccount_coordinate_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrazosPropertySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tax_year", models.PositiveIntegerField(db_index=True)),
                ("outcome", models.CharField(choices=[("completed", "Completed"), ("partial", "Partial")], max_length=16)),
                ("cad_source_year", models.PositiveIntegerField()),
                ("gis_source_year", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "BCAD Property Snapshot",
                "verbose_name_plural": "BCAD Property Snapshots",
            },
        ),
        migrations.AddIndex(
            model_name="brazospropertysnapshot",
            index=models.Index(fields=["tax_year", "is_active"], name="brazos_cad__tax_yea_7e098a_idx"),
        ),
        migrations.AddConstraint(
            model_name="brazospropertysnapshot",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("is_active",), name="brazoscad_one_active_snapshot"),
        ),
    ]
