# Generated by Django 5.2.17 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0007_brazospropertysnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinateEnrichmentAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_year", models.PositiveIntegerField()),
                ("target_year", models.PositiveIntegerField(db_index=True)),
                ("outcome", models.CharField(choices=[("analyzed", "Analyzed"), ("applied", "Applied"), ("noop", "No-op"), ("rejected", "Rejected")], max_length=16)),
                ("minimum_match_rate", models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("cleanup_state", models.CharField(choices=[("retained", "Retained"), ("cleaned", "Cleaned"), ("cleanup_failed", "Cleanup failed")], default="retained", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("snapshot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coordinate_enrichment_audits", to="brazos_cad.brazospropertysnapshot")),
            ],
            options={
                "verbose_name": "BCAD Coordinate Enrichment Audit",
                "verbose_name_plural": "BCAD Coordinate Enrichment Audits",
            },
        ),
        migrations.AddIndex(
            model_name="coordinateenrichmentaudit",
            index=models.Index(fields=["target_year", "created_at"], name="brazos_cad__target__dc6a6b_idx"),
        ),
    ]
