# Generated by Django 5.2.17 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brazos_cad", "0008_coordinateenrichmentaudit")]

    operations = [
        migrations.CreateModel(
            name="BrazosHistoricalCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tax_year", models.PositiveIntegerField(unique=True)),
                ("status", models.CharField(choices=[("available", "Available"), ("unavailable", "Unavailable")], max_length=16)),
                ("failure_category", models.CharField(blank=True, max_length=64)),
                ("recorded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BCAD Historical Coverage",
                "verbose_name_plural": "BCAD Historical Coverage",
            },
        ),
    ]
