# Generated by Django 5.2.7 on 2025-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_propertyrecord_new_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyrecord',
            name='prop_zip_street_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyrecord',
            name='prop_acct_idx',
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='building_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
