# Generated by Django 5.2.7 on 2025-10-15 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_propertyrecord_latitude_propertyrecord_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, max_length=10)),
                ('building_style', models.CharField(blank=True, max_length=10)),
                ('building_class', models.CharField(blank=True, max_length=10)),
                ('quality_code', models.CharField(blank=True, max_length=10)),
                ('condition_code', models.CharField(blank=True, max_length=10)),
                ('year_built', models.IntegerField(blank=True, db_index=True, null=True)),
                ('year_remodeled', models.IntegerField(blank=True, null=True)),
                ('effective_year', models.IntegerField(blank=True, null=True)),
                ('heat_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stories', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('foundation_type', models.CharField(blank=True, max_length=10)),
                ('exterior_wall', models.CharField(blank=True, max_length=10)),
                ('roof_cover', models.CharField(blank=True, max_length=10)),
                ('roof_type', models.CharField(blank=True, max_length=10)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('half_baths', models.IntegerField(blank=True, null=True)),
                ('fireplaces', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='data.propertyrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['account_number', 'building_number'], name='data_buildi_account_2ff891_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtraFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('feature_number', models.IntegerField(blank=True, null=True)),
                ('feature_code', models.CharField(db_index=True, max_length=10)),
                ('feature_description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_code', models.CharField(blank=True, max_length=10)),
                ('condition_code', models.CharField(blank=True, max_length=10)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_features', to='data.propertyrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['account_number', 'feature_code'], name='data_extraf_account_efda0a_idx')],
            },
        ),
    ]
