# Generated by Django 5.2.7 on 2025-10-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_buildingdetail_extrafeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetail',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='buildingdetail',
            name='import_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingdetail',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='extrafeature',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extrafeature',
            name='import_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='extrafeature',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='buildingdetail',
            index=models.Index(fields=['is_active', 'import_date'], name='data_buildi_is_acti_7edc17_idx'),
        ),
        migrations.AddIndex(
            model_name='extrafeature',
            index=models.Index(fields=['is_active', 'import_date'], name='data_extraf_is_acti_39170a_idx'),
        ),
    ]
