# Generated by Django 5.2.11 on 2026-04-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_propertyrecord_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='is_data_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='is_residential',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='state_class',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
