# Generated by Django 5.2.17 on 2026-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_propertyjurisdictionexemption_taxunitrate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assessmenthistory",
            name="unique_assessment_history_per_year",
        ),
        migrations.RemoveConstraint(
            model_name="propertyjurisdictionexemption",
            name="unique_jur_exemption_per_unit_code_year",
        ),
        migrations.RemoveConstraint(
            model_name="taxunitrate",
            name="unique_tax_rate_per_unit_year",
        ),
        migrations.AddField(
            model_name="assessmenthistory",
            name="county",
            field=models.CharField(
                choices=[("harris", "Harris"), ("brazos", "Brazos")],
                db_index=True,
                default="harris",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="propertyjurisdictionexemption",
            name="county",
            field=models.CharField(
                choices=[("harris", "Harris"), ("brazos", "Brazos")],
                db_index=True,
                default="harris",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="taxunitrate",
            name="county",
            field=models.CharField(
                choices=[("harris", "Harris"), ("brazos", "Brazos")],
                db_index=True,
                default="harris",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmenthistory",
            constraint=models.UniqueConstraint(
                fields=("account_number", "tax_year", "county"),
                name="unique_assessment_history_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyjurisdictionexemption",
            constraint=models.UniqueConstraint(
                fields=("account_number", "tax_year", "tax_unit_code", "exemption_code", "county"),
                name="unique_jur_exemption_per_unit_code_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxunitrate",
            constraint=models.UniqueConstraint(
                fields=("tax_year", "tax_unit_code", "county"), name="unique_tax_rate_per_unit_year"
            ),
        ),
    ]
