# Generated by Django 5.2.17 on 2026-09-18 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_remove_assessmenthistory_unique_assessment_history_per_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        choices=[("harris", "Harris"), ("brazos", "Brazos")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("intent", models.CharField(max_length=80)),
                ("requested_year", models.IntegerField(null=True)),
                ("origin", models.CharField(default="operator", max_length=80)),
                ("actor", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(db_index=True, default="running", max_length=32)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("publication_before", models.JSONField(null=True)),
                ("publication_after", models.JSONField(null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "import operation",
                "verbose_name_plural": "Imports",
                "ordering": ("-started_at",),
                "default_permissions": ("view",),
            },
        ),
    ]
