# Generated by Django 5.2.17 on 2026-08-15 19:50

from django.db import migrations, models


def backfill_parcel_geometry_from_harris(apps, schema_editor):
    """Copy lat/long/parcel_id from PropertyRecord into ParcelGeometry."""
    PropertyRecord = apps.get_model("data", "PropertyRecord")
    ParcelGeometry = apps.get_model("data", "ParcelGeometry")
    if not PropertyRecord.objects.exists():
        return
    # Bulk backfill via raw SQL for speed on 1.17M rows.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO data_parcelgeometry
                (account_number, county, latitude, longitude, parcel_id, created_at, updated_at)
            SELECT account_number, 'harris', latitude, longitude, parcel_id, NOW(), NOW()
            FROM data_propertyrecord
            WHERE latitude IS NOT NULL AND longitude IS NOT NULL
        """)


def remove_parcel_geometry(apps, schema_editor):
    ParcelGeometry = apps.get_model("data", "ParcelGeometry")
    ParcelGeometry.objects.filter(county="harris").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_remove_assessmenthistory_unique_assessment_history_per_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_number", models.CharField(db_index=True, max_length=20)),
                (
                    "county",
                    models.CharField(
                        choices=[("harris", "Harris"), ("brazos", "Brazos")],
                        db_index=True,
                        default="harris",
                        max_length=16,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, db_index=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("parcel_id", models.CharField(blank=True, db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="data_parcel_latitud_60ec3a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_number", "county"),
                        name="unique_parcel_geometry_per_account",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_parcel_geometry_from_harris, remove_parcel_geometry),
    ]