# Generated by Django 5.2.17 on 2026-09-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_import_operation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountyWriter",
            fields=[
                (
                    "county",
                    models.CharField(
                        choices=[("harris", "Harris"), ("brazos", "Brazos")],
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("backend_pid", models.IntegerField(null=True)),
                (
                    "operation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.importoperation",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
