# Generated by Django 5.2.17 on 2026-08-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_parcelgeometry"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parcelgeometry",
            name="data_parcel_latitud_60ec3a_idx",
        ),
        migrations.AlterField(
            model_name="parcelgeometry",
            name="parcel_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
