# Generated by Django 5.2.17 on 2026-08-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_drop_unused_parcelgeometry_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyrecord",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="propertyrecord",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="propertyrecord",
            name="parcel_id",
        ),
    ]
