# Generated by Django 5.2.17 on 2026-09-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_county_writer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importoperation",
            options={
                "default_permissions": ("view",),
                "ordering": ("-started_at",),
                "permissions": (("recover_county_writer", "Can recover a county writer"),),
                "verbose_name": "import operation",
                "verbose_name_plural": "Imports",
            },
        ),
        migrations.CreateModel(
            name="ImportAuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("actor", models.CharField(max_length=150)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("evidence", models.JSONField(default=dict)),
                ("result", models.CharField(max_length=32)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="data.importoperation",
                    ),
                ),
            ],
            options={
                "default_permissions": ("view",),
            },
        ),
    ]
