# Generated by Django 5.2.17 on 2026-08-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_drop_inline_coordinate_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcelgeometry",
            name="parcel_id",
        ),
    ]
