# Generated by Django 5.2.17 on 2026-09-18 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_import_writer_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        choices=[("harris", "Harris"), ("brazos", "Brazos")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("state", models.CharField(db_index=True, default="preparing", max_length=32)),
                ("storage_schema", models.CharField(max_length=63, unique=True)),
                ("baseline", models.JSONField(default=dict)),
                ("sources", models.JSONField(default=list)),
                ("request", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate",
                        to="data.importoperation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "default_permissions": ("view",),
            },
        ),
    ]
