# Generated by Django 5.2.17 on 2026-09-18 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_importcandidate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importoperation",
            options={
                "default_permissions": ("view",),
                "ordering": ("-started_at",),
                "permissions": (
                    ("recover_county_writer", "Can recover a county writer"),
                    ("approve_import_coverage", "Can review import coverage exceptions"),
                ),
                "verbose_name": "import operation",
                "verbose_name_plural": "Imports",
            },
        ),
    ]
