# Generated by Django 5.2.17 on 2026-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_repair_brazos_gross_bases"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importoperation",
            options={
                "default_permissions": ("view",),
                "ordering": ("-started_at",),
                "permissions": (
                    ("recover_county_writer", "Can recover a county writer"),
                    ("approve_import_coverage", "Can review import coverage exceptions"),
                    ("cleanup_import_sources", "Can clean obsolete import sources"),
                ),
                "verbose_name": "import operation",
                "verbose_name_plural": "Imports",
            },
        ),
        migrations.AddField(
            model_name="importcandidate",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="importcandidate",
            name="rejected_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="importcandidate",
            name="superseded_at",
            field=models.DateTimeField(null=True),
        ),
    ]
