# Generated by Django 5.2.17 on 2026-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brazos_cad", "0003_remove_propertyentity_adopted_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyaccount",
            name="class_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="living_area",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="mailing_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="mailing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="mailing_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="mailing_zip",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="propertyaccount",
            name="year_built",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
